name: Readme Scribe

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update readme automatically"
          branch: main

