name: Readme Scribe

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md"
          writeTo: "README.md"

      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          commit-message: 'chore: update readme automatically'
          committer: GitHub <noreply@github.com>
          branch: feat/docs
          delete-branch: true
          title: 'chore: update readme automatically'
          assignees: MM25Zamanian
          reviewers: MM25Zamanian
